<?php
function mtb_blog() {
	$labels = array(
		'name'                  => _x( 'Timeline Blogs', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'Timeline Blog', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Timeline Blogs', 'text_domain' ),
		'name_admin_bar'        => __( 'Timeline Blog', 'text_domain' ),
		'archives'              => __( 'Blog Archives', 'text_domain' ),
		'attributes'            => __( 'Blog Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Blog:', 'text_domain' ),
		'all_items'             => __( 'All Blogs', 'text_domain' ),
		'add_new_item'          => __( 'Add New Blog', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Blog', 'text_domain' ),
		'edit_item'             => __( 'Edit Blog', 'text_domain' ),
		'update_item'           => __( 'Update Blog', 'text_domain' ),
		'view_item'             => __( 'View Blogs', 'text_domain' ),
		'view_items'            => __( 'View Blogs', 'text_domain' ),
		'search_items'          => __( 'Search Blog', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
		'items_list'            => __( 'Blog list', 'text_domain' ),
		'items_list_navigation' => __( 'Blogs list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter blogs list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Timeline Blog', 'text_domain' ),
		'description'           => __( 'Timeline Blog Description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'excerpt', 'author', 'thumbnail', 'comments', 'trackbacks', 'revisions', 'custom-fields', 'page-attributes', 'post-formats', ),
		//'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-calendar',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true,
	);
	register_post_type( 'tmblog', $args );
}
add_action( 'init', 'mtb_blog', 0 );
?>